
import os
import json
import yaml

# C头文件模板
TEMPLATE_HEADER_FRONT = '''// This header file is automatically generated by super_config.py
// DO NOT EDIT MANUALLY - changes will be lost

#ifndef SUPER_CONFIG_H
#define SUPER_CONFIG_H

#include "typedef.h"

'''

TEMPLATE_HEADER_END = '''
extern ST_D_SIM d_sim;
void init_d_sim();

#endif // SUPER_CONFIG_H
'''

TEMPLATE_C_FRONT = '''// This source file is automatically generated by super_config.py
// DO NOT EDIT MANUALLY - changes will be lost

#include "super_config.h"
#include <string.h>

ST_D_SIM d_sim;

void init_d_sim() {
'''

TEMPLATE_C_END = '''
}
'''


class SuperConfig:
    def __init__(self, motor_name=None):
        self.motor_name = motor_name
        self.config_data = {}
        self.motor_params = {}

        # 生成代码内容
        self.header_content = ""
        self.c_content = ""
        
        # 路径
        self.base_path = os.path.dirname(os.path.abspath(__file__))
        self.c_path = os.path.join(self.base_path, "frameworkCodes", "c")
        self.motor_lib_path = os.path.join(self.base_path, "input_motorLibrary", "motor_library.json")
    
    def load_motor_library(self):
        "加载电机参数库"
        with open(self.motor_lib_path, 'r', encoding='utf-8') as f:
            self.motor_library = json.load(f)
        return self.motor_library
    
    def load_user_config(self, config_file="user_config.yaml"):
        "加载用户YAML配置"
        config_path = os.path.join(self.base_path, config_file)
        with open(config_path, 'r', encoding='utf-8') as f:
            self.user_config = yaml.safe_load(f)
        return self.user_config
    
    def get_motor_params(self, motor_name):
        """从电机库获取指定电机的参数"""
        if motor_name in self.motor_library:
            params = self.motor_library[motor_name]["基本参数"]
            return {
                'npp': params["极对数 [1]"],
                'IN': params["额定电流 [Arms]"],
                'R': params["定子电阻 [Ohm]"],
                'Ld': params["定子D轴电感 [mH]"] * 1e-3,  # mH -> H
                'Lq': params["定子Q轴电感 [mH]"] * 1e-3,
                'KE': params["额定反电势系数 [Wb]"],
                'Js': params["转动惯量 [kg.cm^2]"] * 1e-6,  # kg.cm^2 -> kg.m^2
                'Vdc': params["母线电压 [Vdc]"],
            }
        return None
    

    def parse_config_to_structs(self):
        """将配置解析为C结构体定义"""
        data = {}

        # 合并所有配置节
        for section in ['simulation', 'motor', 'control', 'test', 'output']:
            if section in self.user_config:
                section_data = {}
                for key, val in self.user_config[section].items():
                    # 解析 key.section.item 格式
                    parts = key.split('.')
                    if len(parts) >= 2:
                        # 取最后一部分作为结构体成员名
                        member_name = parts[-1]
                        section_data[member_name] = val
                    else:
                        section_data[key] = val

                # 对于motor部分，如果选择了点击名，从电机库加载
                if section == 'motor' and self.motor_name:
                    motor_params = self.get_motor_params(self.motor_name)
                    if motor_params:
                        section_data.update(motor_params)
                        # 确保NAME字段使用选择的电机名
                        section_data['NAME'] = self.motor_name

                data[section] = section_data

        return data
    
    def generate_header(self, data):
        """生成C头文件内容"""
        header = TEMPLATE_HEADER_FRONT

        # 生成结构体定义
        for struct_name, members in data.items():
            header += f"\ntypedef struct {{\n"
            for member_name, value in members.items():
                # 根据值类型决定C类型
                if isinstance(value, bool):
                    header += f"    BOOL {member_name};\n"
                elif isinstance(value, str):
                    header += f"    char {member_name}[128];\n"
                elif isinstance(value, int):
                    header += f"    long {member_name};\n"
                else:
                    header += f"    REAL {member_name};\n"
            header += f"}} ST_{struct_name.upper()};\n"

        # 生成顶层结构体
        header += f"\ntypedef struct {{\n"
        for struct_name in data.keys():
            header += f"    ST_{struct_name.upper()} {struct_name.lower()};\n"
        header += f"}} ST_D_SIM;\n"

        header += TEMPLATE_HEADER_END
        return header

    def generate_c_source(self, data):
        """生成C源文件内容"""
        c_source = TEMPLATE_C_FRONT

        # 生成初始化代码
        for struct_name, members in data.items():
            for member_name, value in members.items():
                struct_prefix = struct_name.lower()
                if isinstance(value, bool):
                    c_source += f"    d_sim.{struct_prefix}.{member_name} = {str(value).upper()};\n"
                elif isinstance(value, str):
                    c_source += f'    strcpy(d_sim.{struct_prefix}.{member_name}, "{value}");\n'
                elif isinstance(value, int):
                    c_source += f"    d_sim.{struct_prefix}.{member_name} = {value};\n"
                else:
                    c_source += f"    d_sim.{struct_prefix}.{member_name} = {value};\n"
            c_source += "\n"

        c_source += TEMPLATE_C_END
        return c_source
    
    def update_super_config(self):
        """更新super_config.h和super_config.c文件"""
        data = self.parse_config_to_structs()

        # 生成代码
        self.header_content = self.generate_header(data)
        self.c_content = self.generate_c_source(data)

        # 写入文件
        header_path = os.path.join(self.c_path, "super_config.h")
        c_path = os.path.join(self.c_path, "super_config.c")

        with open(header_path, 'w', encoding='utf-8') as f:
            f.write(self.header_content)

        with open(c_path, 'w', encoding='utf-8') as f:
            f.write(self.c_content)

        print(f"[super_config] Generated {header_path}")
        print(f"[super_config] Generated {c_path}")

        return True

    

    def list_available_motors(self):
        """列出可用电机"""
        motors = self.load_motor_library()
        print("\nAvailable motors:")
        for name in motors.keys():
            print(f"  - {name}")
        return list(motors.keys())



def main():
    """示例用法"""
    config = SuperConfig("SEW100W")

    # 加载配置
    config.load_motor_library()
    config.load_user_config()

    # 列出可用电机
    config.list_available_motors()

    # 生成C配置文件
    config.update_super_config()

if __name__ == "__main__":
    main()