simulation:
  sim.CL_TS: 5.0e-05
  sim.NUMBER_OF_STEPS: 4000
  sim.MACHINE_SIM_PER_CONTROL: 1
  sim.MODE_SELECT: 4
  sim.NUNMBER_OF_STEPS: 4000
motor:
  motor.NAME: SEW100W
  motor.npp: 4
  motor.IN: 3.5
  motor.R: 0.475
  motor.Ld: 0.00205
  motor.Lq: 0.00205
  motor.KE: 0.0107
  motor.Js: 3.5e-06
  motor.Vdc: 48
control:
  FOC.CURRENT_BW: 100.0
  FOC.SPEED_BW: 10.0
  FOC.VL_EXE_PER_CL_EXE: 10
test:
  test.cmd_speed: 100.0
  test.cmd_iD: 0.0
  test.cmd_iQ: 1.0
  test.cmd_uD: 0.0
  test.cmd_uQ: 5.0
  test.TLoad: 0.0
  test.TLoad_time: 0.1
output:
  output.DATA_FILE: ../dat/test_motor.dat
  output.verbose: true
