// This header file is automatically generated by super_config.py
// DO NOT EDIT MANUALLY - changes will be lost

#ifndef SUPER_CONFIG_H
#define SUPER_CONFIG_H

#include "typedef.h"


typedef struct {
    REAL cl_ts;
    long number_of_steps;
    long machine_sim_per_control;
    long mode_select;
} ST_SIMULATION;

typedef struct {
    char NAME[128];
    long npp;
    REAL IN;
    REAL R;
    REAL Ld;
    REAL Lq;
    REAL KE;
    REAL Js;
    long Vdc;
} ST_MOTOR;

typedef struct {
    REAL current_bw;
    REAL speed_bw;
    long vl_exe_per_cl_exe;
} ST_CONTROL;

typedef struct {
    REAL cmd_speed;
    REAL cmd_id;
    REAL cmd_iq;
    REAL cmd_ud;
    REAL cmd_uq;
    REAL tload;
    REAL tload_time;
} ST_TEST;

typedef struct {
    char data_file[128];
    BOOL verbose;
} ST_OUTPUT;

typedef struct {
    ST_SIMULATION simulation;
    ST_MOTOR motor;
    ST_CONTROL control;
    ST_TEST test;
    ST_OUTPUT output;
} ST_D_SIM;

extern ST_D_SIM d_sim;
void init_d_sim();

#endif // SUPER_CONFIG_H
