// This source file is automatically generated by super_config.py
// DO NOT EDIT MANUALLY - changes will be lost

#include "super_config.h"
#include <string.h>

ST_D_SIM d_sim;

void init_d_sim() {
    d_sim.simulation.CL_TS = 0.0001;
    d_sim.simulation.NUMBER_OF_STEPS = 100000;
    d_sim.simulation.MACHINE_SIM_PER_CONTROL = 1;
    d_sim.simulation.MODE_SELECT = 4;

    strcpy(d_sim.motor.NAME, "SEW100W");
    d_sim.motor.npp = 4;
    d_sim.motor.IN = 3.5;
    d_sim.motor.R = 0.475;
    d_sim.motor.Ld = 0.0020499999999999997;
    d_sim.motor.Lq = 0.0020499999999999997;
    d_sim.motor.KE = 0.0107;
    d_sim.motor.Js = 3.5e-08;
    d_sim.motor.Vdc = 48;

    d_sim.control.CURRENT_BW = 100.0;
    d_sim.control.SPEED_BW = 10.0;
    d_sim.control.VL_EXE_PER_CL_EXE = 10;

    d_sim.test.cmd_speed = 100.0;
    d_sim.test.cmd_iD = 0.0;
    d_sim.test.cmd_iQ = 1.0;
    d_sim.test.TLoad = 0.0;
    d_sim.test.TLoad_time = 0.1;

    strcpy(d_sim.output.DATA_FILE, "../dat/test_motor.dat");
    d_sim.output.verbose = TRUE;


}
