// This header file is automatically generated by super_config.py
// DO NOT EDIT MANUALLY - changes will be lost

#ifndef SUPER_CONFIG_H
#define SUPER_CONFIG_H

#include "typedef.h"


typedef struct {
    REAL CL_TS;
    long NUMBER_OF_STEPS;
    long MACHINE_SIM_PER_CONTROL;
    long MODE_SELECT;
} ST_SIMULATION;

typedef struct {
    char NAME[128];
    long npp;
    REAL IN;
    REAL R;
    REAL Ld;
    REAL Lq;
    REAL KE;
    REAL Js;
    long Vdc;
} ST_MOTOR;

typedef struct {
    REAL CURRENT_BW;
    REAL SPEED_BW;
    long VL_EXE_PER_CL_EXE;
} ST_CONTROL;

typedef struct {
    REAL cmd_speed;
    REAL cmd_iD;
    REAL cmd_iQ;
    REAL TLoad;
    REAL TLoad_time;
} ST_TEST;

typedef struct {
    char DATA_FILE[128];
    BOOL verbose;
} ST_OUTPUT;

typedef struct {
    ST_SIMULATION simulation;
    ST_MOTOR motor;
    ST_CONTROL control;
    ST_TEST test;
    ST_OUTPUT output;
} ST_D_SIM;

extern ST_D_SIM d_sim;
void init_d_sim();

#endif // SUPER_CONFIG_H
